use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn collect_protos(dir: &str) -> Vec<String> {
    let mut files = Vec::new();
    recurse(dir.as_ref(), &mut files);
    files
}

fn recurse(dir: &Path, files: &mut Vec<String>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                recurse(&path, files);
            } else if path.extension().and_then(|e| e.to_str()) == Some("proto") {
                files.push(path.to_string_lossy().to_string());
            }
        }
    }
}

/// Stems of `tests/wpt_data/conformance/*.json` for integration test codegen.
fn wpt_conformance_json_stems(manifest_dir: &Path) -> Vec<String> {
    let dir = manifest_dir
        .join("tests")
        .join("wpt_data")
        .join("conformance");
    let mut stems = Vec::new();
    if let Ok(entries) = fs::read_dir(&dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.extension().and_then(|x| x.to_str()) == Some("json") {
                if let Some(s) = p.file_stem().and_then(|s| s.to_str()) {
                    stems.push(s.to_string());
                }
            }
        }
    }
    stems.sort();
    for p in stems.iter().map(|s| dir.join(format!("{s}.json"))) {
        println!("cargo:rerun-if-changed={}", p.display());
    }
    stems
}

fn rust_test_ident_from_stem(stem: &str) -> String {
    let mut out = String::new();
    for (i, c) in stem.chars().enumerate() {
        let ok = if i == 0 {
            c == '_' || c.is_ascii_alphabetic()
        } else {
            c == '_' || c.is_ascii_alphanumeric()
        };
        out.push(if ok { c } else { '_' });
    }
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out = format!("op_{out}");
    }
    out
}

fn write_wpt_json_tests(out_dir: &Path, stems: &[String]) -> Result<(), Box<dyn std::error::Error>> {
    let path = out_dir.join("wpt_json_tests_generated.rs");
    let mut f = fs::File::create(&path)?;
    writeln!(f, "// Generated by build.rs - do not edit.")?;
    writeln!(
        f,
        "// Two #[test]s per JSON: wpt_json_onnx_* (onnx-runtime) and wpt_json_trtx_* (trtx)."
    )?;
    for stem in stems {
        let ident = rust_test_ident_from_stem(stem);
        writeln!(
            f,
            r#"#[test]
#[cfg(feature = "onnx-runtime")]
fn wpt_json_onnx_{ident}() {{
    const STEM: &str = {stem:?};
    let result = std::panic::catch_unwind(|| wpt_conformance::run_operation_onnx(STEM));
    match result {{
        Ok(Ok(())) => {{}}
        Ok(Err(e)) => {{
            if e.contains("ONNX Runtime")
                && (e.contains("not compatible") || e.contains("Failed to load"))
            {{
                println!(
                    "[SKIP] WPT ONNX {{}}: ONNX Runtime load/version issue. {{}}",
                    STEM,
                    e.lines().next().unwrap_or(&e)
                );
                return;
            }}
            panic!("WPT ONNX failed ({{}}): {{}}", STEM, e);
        }}
        Err(panic_payload) => {{
            let msg = if let Some(s) = panic_payload.downcast_ref::<&str>() {{
                (*s).to_string()
            }} else if let Some(s) = panic_payload.downcast_ref::<String>() {{
                s.clone()
            }} else {{
                "unknown panic".to_string()
            }};
            if msg.contains("ONNX Runtime")
                && (msg.contains("not compatible") || msg.contains("Failed to load"))
            {{
                println!(
                    "[SKIP] WPT ONNX {{}}: ONNX Runtime load/version issue. {{}}",
                    STEM,
                    msg.lines().next().unwrap_or(&msg)
                );
                return;
            }}
            panic!("WPT ONNX panicked ({{}}): {{}}", STEM, msg);
        }}
    }}
}}
"#,
            ident = ident,
            stem = stem,
        )?;
        writeln!(
            f,
            r#"#[test]
#[cfg(any(feature = "trtx-runtime-mock", feature = "trtx-runtime"))]
fn wpt_json_trtx_{ident}() {{
    const STEM: &str = {stem:?};
    let result = std::panic::catch_unwind(|| wpt_conformance::run_operation_trtx(STEM));
    match result {{
        Ok(Ok(())) => {{}}
        Ok(Err(e)) => panic!("WPT TRTX failed ({{}}): {{}}", STEM, e),
        Err(panic_payload) => {{
            let msg = if let Some(s) = panic_payload.downcast_ref::<&str>() {{
                (*s).to_string()
            }} else if let Some(s) = panic_payload.downcast_ref::<String>() {{
                s.clone()
            }} else {{
                "unknown panic".to_string()
            }};
            panic!("WPT TRTX panicked ({{}}): {{}}", STEM, msg);
        }}
    }}
}}
"#,
            ident = ident,
            stem = stem,
        )?;
    }
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    let stems = wpt_conformance_json_stems(&manifest_dir);
    write_wpt_json_tests(&out_dir, &stems)?;

    let mut config = prost_build::Config::new();
    config.bytes(["."]); // Fix clippy::needless_borrows_for_generic_args

    let coreml_dir = "protos/coreml";

    let mut coreml_files = collect_protos(coreml_dir);
    coreml_files.sort();

    // Only compile CoreML protos - ONNX protos come from webnn-onnx-utils
    config.compile_protos(&coreml_files, &[coreml_dir])?;

    println!("cargo:rerun-if-changed=protos");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=OUT_DIR");
    Ok(())
}
