//! TFLite FlatBuffer converter for WebNN graphs.
//!
//! Converts WebNN GraphInfo directly to TFLite flatbuffers using the
//! `flatbuffers` crate and schema generated from `protos/tflite/schema.fbs`.

// Generated by build.rs from protos/tflite/schema.fbs
include!(concat!(env!("OUT_DIR"), "/schema_generated.rs"));

use std::collections::HashMap;

use flatbuffers::{FlatBufferBuilder, WIPOffset};

use crate::error::GraphError;
use crate::graph::{DataType, Dimension, GraphInfo, OperandKind};
use crate::operators::Operation;

use super::{ConvertedGraph, GraphConverter};

pub struct LiteRtConverter;

impl LiteRtConverter {
    pub fn new() -> Self {
        Self
    }
}

impl GraphConverter for LiteRtConverter {
    fn format(&self) -> &'static str {
        "litert"
    }

    fn convert(&self, graph: &GraphInfo) -> Result<ConvertedGraph, GraphError> {
        let bytes = build_native(graph)?;
        Ok(ConvertedGraph {
            format: "litert",
            content_type: "application/octet-stream",
            data: bytes,
            weights_data: None,
        })
    }
}

// ---- Native TFLite conversion ----

struct TfliteContext<'a> {
    fbb: FlatBufferBuilder<'a>,
    tensor_offsets: Vec<WIPOffset<tflite::Tensor<'a>>>,
    opcodes: Vec<WIPOffset<tflite::OperatorCode<'a>>>,
    buffer_data: Vec<Vec<u8>>,
}

impl<'a> TfliteContext<'a> {
    fn new() -> Self {
        Self {
            fbb: FlatBufferBuilder::new(),
            tensor_offsets: Vec::new(),
            opcodes: Vec::new(),
            buffer_data: vec![Vec::new()], // buffer 0 is always empty
        }
    }

    fn add_opcode(&mut self, code: i32, version: i32) -> u32 {
        let deprecated: i8 = match code {
            0 => 0, // ADD
            3 => 3, // CONV_2D
            9 => 9, // FULLY_CONNECTED
            _ => 0,
        };
        let oc = tflite::OperatorCode::create(
            &mut self.fbb,
            &tflite::OperatorCodeArgs {
                deprecated_builtin_code: deprecated,
                builtin_code: tflite::BuiltinOperator(code),
                version,
                custom_code: None,
            },
        );
        let idx = self.opcodes.len() as u32;
        self.opcodes.push(oc);
        idx
    }

    fn add_tensor(
        &mut self,
        name: &str,
        shape: &[i32],
        tfl_type: tflite::TensorType,
        buffer_idx: u32,
    ) -> u32 {
        let name_offset = self.fbb.create_string(name);
        let shape_vec = self.fbb.create_vector(shape);
        let tensor = tflite::Tensor::create(
            &mut self.fbb,
            &tflite::TensorArgs {
                shape: Some(shape_vec),
                type_: tfl_type,
                buffer: buffer_idx,
                name: Some(name_offset),
                quantization: None,
                is_variable: false,
                sparsity: None,
                shape_signature: None,
                has_rank: true,
                variant_tensors: None,
            },
        );
        let idx = self.tensor_offsets.len() as u32;
        self.tensor_offsets.push(tensor);
        idx
    }

    fn add_constant(
        &mut self,
        name: &str,
        shape: &[i32],
        tfl_type: tflite::TensorType,
        data: &[u8],
    ) -> u32 {
        let buf_idx = self.buffer_data.len() as u32;
        self.buffer_data.push(data.to_vec());
        self.add_tensor(name, shape, tfl_type, buf_idx)
    }
}

fn datatype_to_tflite(dt: DataType) -> tflite::TensorType {
    match dt {
        DataType::Float32 => tflite::TensorType::FLOAT32,
        DataType::Float16 => tflite::TensorType::FLOAT16,
        DataType::Int32 => tflite::TensorType::INT32,
        DataType::Uint32 => tflite::TensorType::UINT32,
        DataType::Int64 => tflite::TensorType::INT64,
        DataType::Uint64 => tflite::TensorType::UINT64,
        DataType::Int8 => tflite::TensorType::INT8,
        DataType::Uint8 => tflite::TensorType::UINT8,
        DataType::Int4 => tflite::TensorType::INT4,
        DataType::Uint4 => panic!("Uint4 not supported in TFLite"),
    }
}

fn dimensions_to_i32(shape: &[Dimension]) -> Vec<i32> {
    shape
        .iter()
        .map(|d| match d {
            Dimension::Static(n) => *n as i32,
            Dimension::Dynamic(_) => -1,
        })
        .collect()
}

/// Standard TFLite op codes matching tensorflow/lite/schema/schema.fbs.
mod std_op {
    pub const ADD: i32 = 0;
    pub const FLOOR: i32 = 8;
    pub const RELU: i32 = 19;
    pub const RESHAPE: i32 = 22;
    pub const SOFTMAX: i32 = 25;
    pub const TANH: i32 = 28;
    pub const LOGISTIC: i32 = 14;
    pub const SUB: i32 = 41;
    pub const DIV: i32 = 42;
    pub const NEG: i32 = 59;
    pub const SIN: i32 = 66;
    pub const COS: i32 = 108;
    pub const EQUAL: i32 = 71;
    pub const NOT_EQUAL: i32 = 72;
    pub const LOG: i32 = 73;
    pub const SQRT: i32 = 75;
    pub const POW: i32 = 78;
    pub const LOGICAL_OR: i32 = 84;
    pub const LOGICAL_AND: i32 = 86;
    pub const LOGICAL_NOT: i32 = 87;
    pub const LEAKY_RELU: i32 = 98;
    pub const ABS: i32 = 101;
    pub const CEIL: i32 = 104;
    pub const MAXIMUM: i32 = 55;
    pub const MINIMUM: i32 = 57;
    pub const LESS: i32 = 58;
    pub const GREATER: i32 = 61;
    pub const GREATER_EQUAL: i32 = 62;
    pub const LESS_EQUAL: i32 = 63;
    pub const PRELU: i32 = 54;
    pub const EXP: i32 = 47;
    pub const MUL: i32 = 18;
    pub const CONV_2D: i32 = 3;
    pub const MAX_POOL_2D: i32 = 17;
    pub const AVERAGE_POOL_2D: i32 = 1;
    pub const CONCATENATION: i32 = 2;
    pub const BATCH_MATMUL: i32 = 126;
}

fn tflite_opcode(op: &Operation) -> Option<i32> {
    match op {
        Operation::Relu { .. } => Some(std_op::RELU),
        Operation::Sigmoid { .. } => Some(std_op::LOGISTIC),
        Operation::Tanh { .. } => Some(std_op::TANH),
        Operation::Softmax { .. } => Some(std_op::SOFTMAX),
        Operation::Add { .. } => Some(std_op::ADD),
        Operation::Sub { .. } => Some(std_op::SUB),
        Operation::Mul { .. } => Some(std_op::MUL),
        Operation::Div { .. } => Some(std_op::DIV),
        Operation::Abs { .. } => Some(std_op::ABS),
        Operation::Neg { .. } => Some(std_op::NEG),
        Operation::Exp { .. } => Some(std_op::EXP),
        Operation::Log { .. } => Some(std_op::LOG),
        Operation::Sqrt { .. } => Some(std_op::SQRT),
        Operation::Ceil { .. } => Some(std_op::CEIL),
        Operation::Floor { .. } => Some(std_op::FLOOR),
        Operation::Sin { .. } => Some(std_op::SIN),
        Operation::Cos { .. } => Some(std_op::COS),
        Operation::Pow { .. } => Some(std_op::POW),
        Operation::Max { .. } => Some(std_op::MAXIMUM),
        Operation::Min { .. } => Some(std_op::MINIMUM),
        Operation::Lesser { .. } => Some(std_op::LESS),
        Operation::Greater { .. } => Some(std_op::GREATER),
        Operation::LesserOrEqual { .. } => Some(std_op::LESS_EQUAL),
        Operation::GreaterOrEqual { .. } => Some(std_op::GREATER_EQUAL),
        Operation::NotEqual { .. } => Some(std_op::NOT_EQUAL),
        Operation::Equal { .. } => Some(std_op::EQUAL),
        Operation::Cast { .. } => Some(53),
        Operation::Pad { .. } => Some(34),
        Operation::Slice { .. } => Some(65),
        Operation::Split { .. } => Some(49),
        Operation::LogicalNot { .. } => Some(std_op::LOGICAL_NOT),
        Operation::LogicalAnd { .. } => Some(std_op::LOGICAL_AND),
        Operation::LogicalOr { .. } => Some(std_op::LOGICAL_OR),
        Operation::Prelu { .. } => Some(std_op::PRELU),
        Operation::LeakyRelu { .. } => Some(std_op::LEAKY_RELU),
        Operation::Conv2d { .. } => Some(std_op::CONV_2D),
        Operation::MaxPool2d { .. } => Some(std_op::MAX_POOL_2D),
        Operation::AveragePool2d { .. } => Some(std_op::AVERAGE_POOL_2D),
        Operation::Reshape { .. } => Some(std_op::RESHAPE),
        Operation::Concat { .. } => Some(std_op::CONCATENATION),
        Operation::Matmul { .. } => Some(std_op::BATCH_MATMUL),
        Operation::Gemm { .. } => Some(std_op::BATCH_MATMUL),
        Operation::Identity { .. } => None,
        _ => None,
    }
}

fn build_native(graph: &GraphInfo) -> Result<Vec<u8>, GraphError> {
    let mut ctx = TfliteContext::new();

    // Map operand IDs to TFLite tensor indices
    let mut tensor_map: HashMap<u32, u32> = HashMap::new();

    // Register all operands as TFLite tensors
    for (i, operand) in graph.operands.iter().enumerate() {
        let id = i as u32;
        let shape = dimensions_to_i32(&operand.descriptor.shape);
        let tfl_type = datatype_to_tflite(operand.descriptor.data_type);
        let name = operand
            .name
            .clone()
            .unwrap_or_else(|| format!("operand_{}", id));

        let tensor_idx = if operand.kind == OperandKind::Constant {
            if let Some(const_data) = graph.constant_operand_ids_to_handles.get(&id) {
                ctx.add_constant(&name, &shape, tfl_type, &const_data.data)
            } else {
                ctx.add_tensor(&name, &shape, tfl_type, 0)
            }
        } else {
            ctx.add_tensor(&name, &shape, tfl_type, 0)
        };
        tensor_map.insert(id, tensor_idx);
    }

    // Build operators
    let mut operator_offsets: Vec<WIPOffset<tflite::Operator<'_>>> = Vec::new();

    for op in &graph.operations {
        // Identity is a no-op: alias output tensor to input tensor
        if let Operation::Identity { input, outputs, .. } = op {
            let input_tensor = *tensor_map.get(input).unwrap_or(input);
            for out_id in outputs {
                tensor_map.insert(*out_id, input_tensor);
            }
            continue;
        }

        let tfl_opcode = match tflite_opcode(op) {
            Some(c) => c,
            None => {
                return Err(GraphError::ConversionFailed {
                    format: "litert".to_string(),
                    reason: format!("unsupported operation: {op:?}"),
                });
            }
        };

        let opcode_idx = ctx.add_opcode(tfl_opcode, 1);

        // Collect input tensor indices
        let input_ids = op.inputs();
        let inputs: Vec<i32> = input_ids
            .iter()
            .map(|&id| *tensor_map.get(&id).unwrap_or(&id) as i32)
            .collect();

        // Collect output tensor indices
        let output_ids = op.outputs();
        let outputs: Vec<i32> = output_ids
            .iter()
            .map(|&id| *tensor_map.get(&id).unwrap_or(&id) as i32)
            .collect();

        let inputs_vec = ctx.fbb.create_vector(&inputs);
        let outputs_vec = ctx.fbb.create_vector(&outputs);

        let tfl_op = tflite::Operator::create(
            &mut ctx.fbb,
            &tflite::OperatorArgs {
                opcode_index: opcode_idx,
                inputs: Some(inputs_vec),
                outputs: Some(outputs_vec),
                builtin_options: None,
                builtin_options_type: tflite::BuiltinOptions::NONE,
                custom_options: None,
                custom_options_format: tflite::CustomOptionsFormat::FLEXBUFFERS,
                mutating_variable_inputs: None,
                intermediates: None,
                large_custom_options_offset: 0,
                large_custom_options_size: 0,
                builtin_options_2: None,
                builtin_options_2_type: tflite::BuiltinOptions2::NONE,
                debug_metadata_index: -1,
            },
        );
        operator_offsets.push(tfl_op);
    }

    // Build subgraph
    let inputs_vec = ctx.fbb.create_vector(
        &graph
            .input_operands
            .iter()
            .map(|&id| *tensor_map.get(&id).unwrap_or(&id) as i32)
            .collect::<Vec<_>>(),
    );
    let outputs_vec = ctx.fbb.create_vector(
        &graph
            .output_operands
            .iter()
            .map(|&id| *tensor_map.get(&id).unwrap_or(&id) as i32)
            .collect::<Vec<_>>(),
    );
    let tensors_vec = ctx.fbb.create_vector(&ctx.tensor_offsets);
    let operators_vec = ctx.fbb.create_vector(&operator_offsets);
    let name = ctx.fbb.create_string("rustnn_graph");

    let subgraph = tflite::SubGraph::create(
        &mut ctx.fbb,
        &tflite::SubGraphArgs {
            tensors: Some(tensors_vec),
            inputs: Some(inputs_vec),
            outputs: Some(outputs_vec),
            operators: Some(operators_vec),
            name: Some(name),
            debug_metadata_index: -1,
        },
    );

    // Build buffers
    let mut buffer_offsets: Vec<WIPOffset<tflite::Buffer<'_>>> = Vec::new();
    for data in &ctx.buffer_data {
        let data_vec = ctx.fbb.create_vector(data.as_slice());
        let buf = tflite::Buffer::create(
            &mut ctx.fbb,
            &tflite::BufferArgs {
                data: Some(data_vec),
                offset: 0,
                size: 0,
            },
        );
        buffer_offsets.push(buf);
    }

    // Metadata buffer for reduced_precision_support (required by LiteRT)
    let meta_data_str = "fp16accfp32";
    let meta_data_vec = ctx.fbb.create_vector(meta_data_str.as_bytes());
    let meta_buf = tflite::Buffer::create(
        &mut ctx.fbb,
        &tflite::BufferArgs {
            data: Some(meta_data_vec),
            offset: 0,
            size: 0,
        },
    );
    let meta_buf_idx = buffer_offsets.len() as u32;
    buffer_offsets.push(meta_buf);

    let buffers_vec = ctx.fbb.create_vector(&buffer_offsets);
    let opcodes_vec = ctx.fbb.create_vector(&ctx.opcodes);
    let subgraphs_vec = ctx.fbb.create_vector(&[subgraph]);
    let description = ctx.fbb.create_string("flatbuffer_direct");

    // SignatureDef (required by LiteRT v2.x)
    let sig_input_maps: Vec<WIPOffset<tflite::TensorMap<'_>>> = graph
        .input_operands
        .iter()
        .map(|&id| {
            let name = ctx.fbb.create_string(
                graph
                    .operand(id)
                    .and_then(|o| o.name.as_deref())
                    .unwrap_or("input"),
            );
            let tensor_idx = *tensor_map.get(&id).unwrap_or(&id);
            tflite::TensorMap::create(
                &mut ctx.fbb,
                &tflite::TensorMapArgs {
                    name: Some(name),
                    tensor_index: tensor_idx,
                },
            )
        })
        .collect();
    let sig_output_maps: Vec<WIPOffset<tflite::TensorMap<'_>>> = graph
        .output_operands
        .iter()
        .map(|&id| {
            let name = ctx.fbb.create_string(
                graph
                    .operand(id)
                    .and_then(|o| o.name.as_deref())
                    .unwrap_or("output"),
            );
            let tensor_idx = *tensor_map.get(&id).unwrap_or(&id);
            tflite::TensorMap::create(
                &mut ctx.fbb,
                &tflite::TensorMapArgs {
                    name: Some(name),
                    tensor_index: tensor_idx,
                },
            )
        })
        .collect();
    let sig_input_vec = ctx.fbb.create_vector(&sig_input_maps);
    let sig_output_vec = ctx.fbb.create_vector(&sig_output_maps);
    let sig_key = ctx.fbb.create_string("serving_default");
    let sig_def = tflite::SignatureDef::create(
        &mut ctx.fbb,
        &tflite::SignatureDefArgs {
            inputs: Some(sig_input_vec),
            outputs: Some(sig_output_vec),
            signature_key: Some(sig_key),
            subgraph_index: 0,
        },
    );
    let sig_defs = ctx.fbb.create_vector(&[sig_def]);

    // Metadata (reduced_precision_support)
    let meta_name = ctx.fbb.create_string("reduced_precision_support");
    let meta_entry = tflite::Metadata::create(
        &mut ctx.fbb,
        &tflite::MetadataArgs {
            name: Some(meta_name),
            buffer: meta_buf_idx,
        },
    );
    let metadata = ctx.fbb.create_vector(&[meta_entry]);

    let model = tflite::Model::create(
        &mut ctx.fbb,
        &tflite::ModelArgs {
            version: 3,
            operator_codes: Some(opcodes_vec),
            subgraphs: Some(subgraphs_vec),
            description: Some(description),
            buffers: Some(buffers_vec),
            metadata_buffer: None,
            metadata: Some(metadata),
            signature_defs: Some(sig_defs),
        },
    );

    ctx.fbb.finish(model, Some("TFL3"));
    Ok(ctx.fbb.finished_data().to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ConstantData;
    use crate::graph::{
        DataType, GraphInfo, Operand, OperandDescriptor, OperandKind, to_dimension_vector,
    };
    use crate::operators::Operation;
    use std::collections::HashMap;

    fn s(shape: &[u32]) -> Vec<crate::graph::Dimension> {
        to_dimension_vector(shape)
    }

    fn op(op_type: &str, inputs: &[u32], outputs: &[u32]) -> Operation {
        Operation::from_json_attributes(op_type, inputs, outputs, &serde_json::Value::Null)
            .unwrap_or_else(|| panic!("unsupported op: {op_type}"))
    }

    fn make_unary(op_type: &str, shape: Vec<u32>) -> GraphInfo {
        let desc = OperandDescriptor {
            data_type: DataType::Float32,
            shape: s(&shape),
            pending_permutation: vec![],
        };
        GraphInfo {
            operands: vec![
                Operand {
                    kind: OperandKind::Input,
                    descriptor: desc.clone(),
                    name: Some("x".into()),
                },
                Operand {
                    kind: OperandKind::Output,
                    descriptor: desc.clone(),
                    name: Some("y".into()),
                },
            ],
            input_operands: vec![0],
            output_operands: vec![1],
            operations: vec![op(op_type, &[0], &[1])],
            constant_operand_ids_to_handles: HashMap::new(),
            id_to_constant_tensor_operand_map: HashMap::new(),
            quantized: false,
        }
    }

    fn make_binary(op_type: &str, shape: Vec<u32>) -> GraphInfo {
        let desc = OperandDescriptor {
            data_type: DataType::Float32,
            shape: s(&shape),
            pending_permutation: vec![],
        };
        GraphInfo {
            operands: vec![
                Operand {
                    kind: OperandKind::Input,
                    descriptor: desc.clone(),
                    name: Some("a".into()),
                },
                Operand {
                    kind: OperandKind::Input,
                    descriptor: desc.clone(),
                    name: Some("b".into()),
                },
                Operand {
                    kind: OperandKind::Output,
                    descriptor: desc.clone(),
                    name: Some("c".into()),
                },
            ],
            input_operands: vec![0, 1],
            output_operands: vec![2],
            operations: vec![op(op_type, &[0, 1], &[2])],
            constant_operand_ids_to_handles: HashMap::new(),
            id_to_constant_tensor_operand_map: HashMap::new(),
            quantized: false,
        }
    }

    fn convert_ok(graph: &GraphInfo) -> Vec<u8> {
        let converter = LiteRtConverter::new();
        let result = converter.convert(graph).expect("conversion failed");
        assert!(!result.data.is_empty());
        // Verify TFL3 magic
        assert_eq!(&result.data[4..8], b"TFL3", "missing TFL3 magic in output");
        result.data
    }

    #[test]
    fn test_dump_model_bytes() {
        let graph = make_unary("abs", vec![4]);
        let bytes = convert_ok(&graph);
        let _ = std::fs::write("/tmp/our_model.bin", &bytes);
        eprintln!("Dumped {} bytes to /tmp/our_model.bin", bytes.len());
    }

    #[test]
    fn test_model_loads_in_litert() {
        let graph = make_unary("abs", vec![4]);
        let bytes = convert_ok(&graph);
        match litert::Model::from_bytes(bytes.to_vec()) {
            Ok(model) => eprintln!(
                "Model loaded OK, signatures={}",
                model.signature_count().unwrap_or(0)
            ),
            Err(e) => panic!("Model rejected: {e}"),
        }
    }

    #[test]
    fn test_format_name() {
        assert_eq!(LiteRtConverter::new().format(), "litert");
    }

    #[test]
    fn test_reshape() {
        convert_ok(&make_unary("reshape", vec![2, 3]));
    }

    #[test]
    fn test_matmul() {
        let a_desc = OperandDescriptor {
            data_type: DataType::Float32,
            shape: s(&[2, 3]),
            pending_permutation: vec![],
        };
        let graph = GraphInfo {
            operands: vec![
                Operand {
                    kind: OperandKind::Input,
                    descriptor: a_desc.clone(),
                    name: Some("a".into()),
                },
                Operand {
                    kind: OperandKind::Input,
                    descriptor: OperandDescriptor {
                        data_type: DataType::Float32,
                        shape: s(&[3, 2]),
                        pending_permutation: vec![],
                    },
                    name: Some("b".into()),
                },
                Operand {
                    kind: OperandKind::Output,
                    descriptor: OperandDescriptor {
                        data_type: DataType::Float32,
                        shape: s(&[2, 2]),
                        pending_permutation: vec![],
                    },
                    name: Some("c".into()),
                },
            ],
            input_operands: vec![0, 1],
            output_operands: vec![2],
            operations: vec![op("matmul", &[0, 1], &[2])],
            constant_operand_ids_to_handles: HashMap::new(),
            id_to_constant_tensor_operand_map: HashMap::new(),
            quantized: false,
        };
        convert_ok(&graph);
    }

    #[test]
    fn test_conv2d() {
        let filter_data: Vec<f32> = vec![1.0; 9];
        let filter_bytes: Vec<u8> = filter_data.iter().flat_map(|f| f.to_le_bytes()).collect();
        let mut constants = HashMap::new();
        constants.insert(
            1,
            ConstantData {
                data: filter_bytes,
                label: Some("w".into()),
            },
        );

        let graph = GraphInfo {
            operands: vec![
                Operand {
                    kind: OperandKind::Input,
                    descriptor: OperandDescriptor {
                        data_type: DataType::Float32,
                        shape: s(&[1, 3, 5, 5]),
                        pending_permutation: vec![],
                    },
                    name: Some("x".into()),
                },
                Operand {
                    kind: OperandKind::Constant,
                    descriptor: OperandDescriptor {
                        data_type: DataType::Float32,
                        shape: s(&[1, 3, 3, 3]),
                        pending_permutation: vec![],
                    },
                    name: Some("w".into()),
                },
                Operand {
                    kind: OperandKind::Output,
                    descriptor: OperandDescriptor {
                        data_type: DataType::Float32,
                        shape: s(&[1, 1, 3, 3]),
                        pending_permutation: vec![],
                    },
                    name: Some("y".into()),
                },
            ],
            input_operands: vec![0],
            output_operands: vec![2],
            operations: vec![op("conv2d", &[0, 1], &[2])],
            constant_operand_ids_to_handles: constants,
            id_to_constant_tensor_operand_map: HashMap::new(),
            quantized: false,
        };
        convert_ok(&graph);
    }

    #[test]
    fn test_all_binary_elementwise() {
        for op_type in &["add", "sub", "mul", "div", "pow"] {
            let graph = make_binary(op_type, vec![4]);
            convert_ok(&graph);
        }
    }

    #[test]
    fn test_all_unary_elementwise() {
        for op_type in &[
            "abs", "neg", "exp", "log", "sqrt", "ceil", "floor", "sin", "cos",
        ] {
            let graph = make_unary(op_type, vec![4]);
            convert_ok(&graph);
        }
    }

    #[test]
    fn test_all_comparison() {
        for op_type in &[
            "lesser",
            "greater",
            "lesserOrEqual",
            "greaterOrEqual",
            "notEqual",
        ] {
            let graph = make_binary(op_type, vec![4]);
            convert_ok(&graph);
        }
    }

    #[test]
    fn test_all_logical() {
        for op_type in &["logicalNot"] {
            let graph = make_unary(op_type, vec![4]);
            convert_ok(&graph);
        }
        for op_type in &["logicalAnd", "logicalOr"] {
            let graph = make_binary(op_type, vec![4]);
            convert_ok(&graph);
        }
    }
}
