//! Protobuf message types generated at build time.
//!
//! [`coreml`] is compiled by `build.rs` from `protos/coreml/*.proto` (CoreML model and MIL
//! program schemas). [`onnx`] re-exports the ONNX protos of the `webnn-onnx-utils` crate so
//! that converted models share one set of types with that crate.

/// CoreML protobuf messages (`CoreML.Specification` package), generated by prost.
// Allow clippy warnings in generated protobuf code.
#[allow(clippy::all, missing_docs)]
pub mod coreml {
    /// `CoreML.Specification.CoreMLModels` package.
    pub mod core_ml_models {
        include!(concat!(
            env!("OUT_DIR"),
            "/core_ml.specification.core_ml_models.rs"
        ));
    }
    /// `CoreML.Specification.MILSpec` package: the MIL program format.
    pub mod mil_spec {
        include!(concat!(
            env!("OUT_DIR"),
            "/core_ml.specification.mil_spec.rs"
        ));
    }
    /// Top-level model, feature descriptions and the classic NeuralNetwork messages.
    pub mod specification {
        // Bring sibling modules into scope to satisfy generated references.
        pub use super::core_ml_models;
        pub use super::mil_spec;

        include!(concat!(env!("OUT_DIR"), "/core_ml.specification.rs"));
    }

    // Re-export to satisfy super::super::StringVector lookups in generated code.
    pub use specification::StringVector;
}

/// ONNX protobuf messages, re-exported from `webnn-onnx-utils` so both crates share one set of types.
pub mod onnx {
    pub use webnn_onnx_utils::protos::onnx::*;
}
